# Generated by Django 2.1.1 on 2019-07-07 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('ticket', 'Ticket'), ('traincard', 'Train card'), ('campus', 'Campus'), ('halftime', 'Half-time Train Card'), ('pass', 'Pass'), ('card', 'Card'), ('mobib', 'MOBIB-card')], default='mobib', max_length=30)),
                ('ticket_number', models.CharField(max_length=128)),
                ('ticket_last_usage', models.DateField()),
                ('departure_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='nmbs.Station')),
                ('destination_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='nmbs.Station')),
                ('stop_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='nmbs.Station')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTrainLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='nmbs.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='TrainLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(max_length=10, unique=True)),
                ('train_serv', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datdep', models.DateField()),
                ('recordid', models.CharField(max_length=64)),
                ('line_no_arr', models.CharField(max_length=64)),
                ('line_no_dep', models.CharField(max_length=64)),
                ('planned_date_arr', models.DateTimeField()),
                ('planned_time_arr', models.TimeField()),
                ('planned_date_dep', models.DateTimeField()),
                ('planned_time_dep', models.TimeField()),
                ('relation', models.CharField(max_length=128)),
                ('relation_direction', models.CharField(max_length=256)),
                ('real_date_dep', models.DateField()),
                ('real_date_arr', models.DateField()),
                ('real_time_dep', models.TimeField()),
                ('real_time_arr', models.TimeField()),
                ('train_serv', models.CharField(max_length=32)),
                ('delay_arr', models.FloatField()),
                ('delay_dep', models.FloatField()),
                ('record_timestamp', models.DateTimeField()),
                ('ptcar_lg_nm_nl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmbs.Station')),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='nmbs.TrainLine')),
            ],
        ),
        migrations.AddField(
            model_name='subscriptiontrainlines',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='nmbs.TrainLine'),
        ),
        migrations.AddField(
            model_name='confirmedtrips',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='nmbs.Subscription'),
        ),
        migrations.AddField(
            model_name='confirmedtrips',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmbs.Trips'),
        ),
        migrations.AlterUniqueTogether(
            name='trips',
            unique_together={('datdep', 'train_no')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontrainlines',
            unique_together={('subscription', 'train')},
        ),
        migrations.AlterUniqueTogether(
            name='confirmedtrips',
            unique_together={('trip', 'subscription')},
        ),
    ]
